version: '3'
services:
  db:
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-ppassword"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  back:
    build: back
    tty: true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
